import type { Recipe } from "./types";

function ing(id: string, name: string, amount: string, optional?: boolean): Recipe["ingredients"][number] {
  return { id, name, amount, optional };
}

export const RECIPES: Recipe[] = [
  {
    id: "oat-banana-breakfast",
    title: "Овсянка с бананом",
    description: "Мягкий завтрак с клетчаткой и медленными углеводами — подходит для контроля веса и сахара.",
    imageEmoji: "🥣",
    imageGradient: "from-amber-400/30 via-orange-300/20 to-yellow-200/30",
    prepMinutes: 5,
    cookMinutes: 10,
    servings: 1,
    calories: 320,
    macros: { protein: 12, fat: 8, carbs: 52 },
    ingredients: [
      ing("oats", "Овсяные хлопья", "50 г"),
      ing("milk", "Молоко 1,5%", "200 мл"),
      ing("banana", "Банан", "1 шт."),
      ing("cinnamon", "Корица", "щепотка", true),
    ],
    steps: [
      { order: 1, text: "Доведите молоко до кипения, добавьте овсянку." },
      { order: 2, text: "Варите на слабом огне 7–8 минут, помешивая." },
      { order: 3, text: "Нарежьте банан, добавьте в кашу с корицей." },
      { order: 4, text: "Подавайте тёплым." },
    ],
    tags: {
      goals: ["lose", "maintain", "health", "sleep"],
      conditions: ["none", "diabetes", "insulin_res", "hypertension"],
      mealTypes: ["breakfast"],
    },
    searchIngredients: ["овсянка", "молоко", "банан", "корица"],
  },
  {
    id: "chicken-vegetable-soup",
    title: "Куриный овощной суп",
    description: "Лёгкий согревающий суп с белком и овощами — бережный вариант для ЖКТ.",
    imageEmoji: "🍲",
    imageGradient: "from-emerald-400/30 via-teal-300/20 to-green-200/30",
    prepMinutes: 15,
    cookMinutes: 35,
    servings: 4,
    calories: 185,
    macros: { protein: 18, fat: 6, carbs: 14 },
    ingredients: [
      ing("chicken", "Куриная грудка", "400 г"),
      ing("carrot", "Морковь", "2 шт."),
      ing("potato", "Картофель", "2 шт."),
      ing("zucchini", "Кабачок", "1 шт."),
      ing("onion", "Лук репчатый", "1 шт."),
      ing("water", "Вода", "1,5 л"),
    ],
    steps: [
      { order: 1, text: "Сварите куриную грудку в воде 20 минут, снимите пену." },
      { order: 2, text: "Добавьте нарезанные овощи." },
      { order: 3, text: "Варите ещё 15 минут до мягкости овощей." },
      { order: 4, text: "Достаньте грудку, нарежьте кубиками, верните в суп." },
    ],
    tags: {
      goals: ["lose", "maintain", "health", "pressure"],
      conditions: ["none", "gastritis", "hypertension", "gerd"],
      mealTypes: ["lunch", "dinner"],
    },
    searchIngredients: ["курица", "морковь", "картофель", "кабачок", "лук"],
  },
  {
    id: "baked-salmon-broccoli",
    title: "Лосось с брокколи",
    description: "Блюдо с омега-3 и низким содержанием простых углеводов — для сердца и давления.",
    imageEmoji: "🐟",
    imageGradient: "from-orange-400/30 via-rose-300/20 to-pink-200/30",
    prepMinutes: 10,
    cookMinutes: 20,
    servings: 2,
    calories: 380,
    macros: { protein: 34, fat: 22, carbs: 8 },
    ingredients: [
      ing("salmon", "Филе лосося", "300 г"),
      ing("broccoli", "Брокколи", "250 г"),
      ing("lemon", "Лимон", "1/2 шт."),
      ing("olive", "Оливковое масло", "1 ст. л."),
      ing("garlic", "Чеснок", "1 зубчик", true),
    ],
    steps: [
      { order: 1, text: "Разогрейте духовку до 190 °C." },
      { order: 2, text: "Выложите лосось и брокколи на противень, сбрызните маслом." },
      { order: 3, text: "Запекайте 18–20 минут." },
      { order: 4, text: "Подавайте с лимоном." },
    ],
    tags: {
      goals: ["lose", "maintain", "health", "pressure"],
      conditions: ["none", "hypertension", "heart", "diabetes"],
      mealTypes: ["lunch", "dinner"],
    },
    searchIngredients: ["лосось", "брокколи", "лимон", "масло", "чеснок"],
  },
  {
    id: "cottage-cheese-bowl",
    title: "Творожный боул с ягодами",
    description: "Быстрый белковый перекус или завтрак для набора мышечной массы.",
    imageEmoji: "🫐",
    imageGradient: "from-violet-400/30 via-purple-300/20 to-fuchsia-200/30",
    prepMinutes: 5,
    cookMinutes: 0,
    servings: 1,
    calories: 290,
    macros: { protein: 28, fat: 10, carbs: 22 },
    ingredients: [
      ing("cottage", "Творог 5%", "180 г"),
      ing("berries", "Ягоды замороженные", "80 г"),
      ing("honey", "Мёд", "1 ч. л.", true),
      ing("nuts", "Миндаль", "10 г", true),
    ],
    steps: [
      { order: 1, text: "Выложите творог в миску." },
      { order: 2, text: "Добавьте ягоды и мёд." },
      { order: 3, text: "Посыпьте миндалём и подавайте." },
    ],
    tags: {
      goals: ["gain", "maintain", "health"],
      conditions: ["none", "anemia"],
      mealTypes: ["breakfast", "snack"],
    },
    searchIngredients: ["творог", "ягоды", "мёд", "миндаль"],
  },
  {
    id: "buckwheat-turkey",
    title: "Гречка с индейкой",
    description: "Сбалансированный ужин: сложные углеводы и постный белок.",
    imageEmoji: "🍽️",
    imageGradient: "from-stone-400/30 via-neutral-300/20 to-zinc-200/30",
    prepMinutes: 10,
    cookMinutes: 25,
    servings: 2,
    calories: 410,
    macros: { protein: 32, fat: 12, carbs: 44 },
    ingredients: [
      ing("buckwheat", "Гречка", "120 г"),
      ing("turkey", "Филе индейки", "250 г"),
      ing("onion", "Лук", "1 шт."),
      ing("carrot", "Морковь", "1 шт."),
      ing("water", "Вода", "250 мл"),
    ],
    steps: [
      { order: 1, text: "Отварите гречку до готовности." },
      { order: 2, text: "Обжарьте индейку с луком и морковью 10 минут." },
      { order: 3, text: "Добавьте немного воды, тушите 12 минут." },
      { order: 4, text: "Подавайте с гречкой." },
    ],
    tags: {
      goals: ["lose", "maintain", "health", "pressure"],
      conditions: ["none", "hypertension", "diabetes", "gastritis"],
      mealTypes: ["lunch", "dinner"],
    },
    searchIngredients: ["гречка", "индейка", "лук", "морковь"],
  },
  {
    id: "vegetable-omelette",
    title: "Овощной омлет",
    description: "Лёгкий белковый завтрак без жарки — подходит при изжоге и контроле веса.",
    imageEmoji: "🍳",
    imageGradient: "from-yellow-400/30 via-lime-300/20 to-green-200/30",
    prepMinutes: 8,
    cookMinutes: 12,
    servings: 1,
    calories: 240,
    macros: { protein: 18, fat: 16, carbs: 6 },
    ingredients: [
      ing("eggs", "Яйца", "2 шт."),
      ing("zucchini", "Кабачок", "100 г"),
      ing("tomato", "Помидор", "1 шт."),
      ing("herbs", "Зелень", "горсть", true),
    ],
    steps: [
      { order: 1, text: "Взбейте яйца, добавьте нарезанные овощи." },
      { order: 2, text: "Вылейте смесь в антипригарную сковороду." },
      { order: 3, text: "Готовьте под крышкой на слабом огне 10–12 минут." },
      { order: 4, text: "Посыпьте зеленью." },
    ],
    tags: {
      goals: ["lose", "maintain", "health"],
      conditions: ["none", "gerd", "gastritis", "hypertension"],
      mealTypes: ["breakfast", "lunch"],
    },
    searchIngredients: ["яйца", "кабачок", "помидор", "зелень"],
  },
  {
    id: "lentil-salad",
    title: "Салат с чечевицей",
    description: "Питательный салат без мяса — много клетчатки и растительного белка.",
    imageEmoji: "🥗",
    imageGradient: "from-lime-400/30 via-green-300/20 to-emerald-200/30",
    prepMinutes: 15,
    cookMinutes: 20,
    servings: 3,
    calories: 265,
    macros: { protein: 14, fat: 9, carbs: 32 },
    ingredients: [
      ing("lentils", "Чечевица", "150 г"),
      ing("cucumber", "Огурец", "1 шт."),
      ing("pepper", "Болгарский перец", "1 шт."),
      ing("olive", "Оливковое масло", "2 ст. л."),
      ing("lemon", "Лимонный сок", "1 ст. л."),
    ],
    steps: [
      { order: 1, text: "Отварите чечевицу до мягкости, остудите." },
      { order: 2, text: "Нарежьте овощи." },
      { order: 3, text: "Смешайте с маслом и лимонным соком." },
      { order: 4, text: "Подавайте охлаждённым или комнатной температуры." },
    ],
    tags: {
      goals: ["lose", "maintain", "health"],
      conditions: ["none", "diabetes", "hypertension", "heart"],
      mealTypes: ["lunch", "dinner"],
    },
    searchIngredients: ["чечевица", "огурец", "перец", "масло", "лимон"],
  },
  {
    id: "rice-chicken-light",
    title: "Рис с курицей (лёгкий)",
    description: "Классическое блюдо для восстановления после нагрузок и набора веса.",
    imageEmoji: "🍚",
    imageGradient: "from-sky-400/30 via-blue-300/20 to-indigo-200/30",
    prepMinutes: 10,
    cookMinutes: 30,
    servings: 2,
    calories: 450,
    macros: { protein: 30, fat: 10, carbs: 58 },
    ingredients: [
      ing("rice", "Рис", "150 г"),
      ing("chicken", "Куриное филе", "300 г"),
      ing("broth", "Вода или бульон", "350 мл"),
      ing("carrot", "Морковь", "1 шт."),
    ],
    steps: [
      { order: 1, text: "Обжарьте курицу до золотистой корочки." },
      { order: 2, text: "Добавьте рис, морковь и жидкость." },
      { order: 3, text: "Тушите под крышкой 25 минут." },
      { order: 4, text: "Дайте настояться 5 минут перед подачей." },
    ],
    tags: {
      goals: ["gain", "maintain", "health"],
      conditions: ["none", "anemia"],
      mealTypes: ["lunch", "dinner"],
    },
    searchIngredients: ["рис", "курица", "морковь"],
  },
  {
    id: "pumpkin-porridge",
    title: "Тыквенная каша",
    description: "Мягкий ужин, богатый калием — подходит при контроле давления.",
    imageEmoji: "🎃",
    imageGradient: "from-orange-500/30 via-amber-400/20 to-yellow-300/30",
    prepMinutes: 10,
    cookMinutes: 25,
    servings: 2,
    calories: 210,
    macros: { protein: 6, fat: 5, carbs: 38 },
    ingredients: [
      ing("pumpkin", "Тыква", "300 г"),
      ing("milk", "Молоко", "200 мл"),
      ing("rice", "Рис круглый", "60 г"),
      ing("honey", "Мёд", "1 ч. л.", true),
    ],
    steps: [
      { order: 1, text: "Нарежьте тыкву кубиками." },
      { order: 2, text: "Сварите с рисом в молоке 20–25 минут." },
      { order: 3, text: "Разомните до нужной консистенции." },
      { order: 4, text: "Добавьте мёд по вкусу." },
    ],
    tags: {
      goals: ["lose", "maintain", "health", "pressure", "sleep"],
      conditions: ["none", "hypertension", "gastritis", "gerd"],
      mealTypes: ["dinner", "breakfast"],
    },
    searchIngredients: ["тыква", "молоко", "рис", "мёд"],
  },
  {
    id: "cucumber-kefir-smoothie",
    title: "Огуречный кефирный напиток",
    description: "Быстрый перекус для жаркого дня — легко усваивается.",
    imageEmoji: "🥤",
    imageGradient: "from-cyan-400/30 via-teal-300/20 to-sky-200/30",
    prepMinutes: 5,
    cookMinutes: 0,
    servings: 1,
    calories: 95,
    macros: { protein: 6, fat: 3, carbs: 10 },
    ingredients: [
      ing("kefir", "Кефир 1%", "250 мл"),
      ing("cucumber", "Огурец", "1 шт."),
      ing("dill", "Укроп", "несколько веточек", true),
    ],
    steps: [
      { order: 1, text: "Нарежьте огурец." },
      { order: 2, text: "Смешайте все ингредиенты в блендере." },
      { order: 3, text: "Подавайте сразу." },
    ],
    tags: {
      goals: ["lose", "maintain", "health"],
      conditions: ["none", "gastritis", "hypertension"],
      mealTypes: ["snack"],
    },
    searchIngredients: ["кефир", "огурец", "укроп"],
  },
];
