/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppChartsRouteImport } from './routes/_app.charts'
import { Route as AppDiaryRouteImport } from './routes/_app.diary'
import { Route as AppGlucoseRouteImport } from './routes/_app.glucose'
import { Route as AppHabitsRouteImport } from './routes/_app.habits'
import { Route as AppHealthRouteImport } from './routes/_app.health'
import { Route as AppHealthFeaturesRouteImport } from './routes/_app.health-features'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppPregnancyRouteImport } from './routes/_app.pregnancy'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppRecipesRouteImport } from './routes/_app.recipes'
import { Route as AppRecoveryRouteImport } from './routes/_app.recovery'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSubscriptionRouteImport } from './routes/_app.subscription'
import { Route as AppVoiceRouteImport } from './routes/_app.voice'
import { Route as AppWorkoutsRouteImport } from './routes/_app.workouts'
import { Route as LegalDocRouteImport } from './routes/legal.$doc'
import { Route as AppHistoryDateRouteImport } from './routes/_app.history.$date'
import { Route as AppRecipesIdRouteImport } from './routes/_app.recipes.$id'
import { Route as AppRecoveryIdRouteImport } from './routes/_app.recovery.$id'
import { Route as AppWorkoutsIdRouteImport } from './routes/_app.workouts.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppChartsRoute = AppChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => AppRoute,
} as any)
const AppDiaryRoute = AppDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AppRoute,
} as any)
const AppGlucoseRoute = AppGlucoseRouteImport.update({
  id: '/glucose',
  path: '/glucose',
  getParentRoute: () => AppRoute,
} as any)
const AppHabitsRoute = AppHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthFeaturesRoute = AppHealthFeaturesRouteImport.update({
  id: '/health-features',
  path: '/health-features',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppPregnancyRoute = AppPregnancyRouteImport.update({
  id: '/pregnancy',
  path: '/pregnancy',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRoute = AppRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AppRoute,
} as any)
const AppRecoveryRoute = AppRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceRoute = AppVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutsRoute = AppWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AppRoute,
} as any)
const LegalDocRoute = LegalDocRouteImport.update({
  id: '/legal/$doc',
  path: '/legal/$doc',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoryDateRoute = AppHistoryDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => AppHistoryRoute,
} as any)
const AppRecipesIdRoute = AppRecipesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRecipesRoute,
} as any)
const AppRecoveryIdRoute = AppRecoveryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRecoveryRoute,
} as any)
const AppWorkoutsIdRoute = AppWorkoutsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppWorkoutsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/ai': typeof AppAiRoute
  '/charts': typeof AppChartsRoute
  '/diary': typeof AppDiaryRoute
  '/glucose': typeof AppGlucoseRoute
  '/habits': typeof AppHabitsRoute
  '/health': typeof AppHealthRoute
  '/health-features': typeof AppHealthFeaturesRoute
  '/history': typeof AppHistoryRouteWithChildren
  '/home': typeof AppHomeRoute
  '/pregnancy': typeof AppPregnancyRoute
  '/profile': typeof AppProfileRoute
  '/recipes': typeof AppRecipesRouteWithChildren
  '/recovery': typeof AppRecoveryRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/voice': typeof AppVoiceRoute
  '/workouts': typeof AppWorkoutsRouteWithChildren
  '/legal/$doc': typeof LegalDocRoute
  '/history/$date': typeof AppHistoryDateRoute
  '/recipes/$id': typeof AppRecipesIdRoute
  '/recovery/$id': typeof AppRecoveryIdRoute
  '/workouts/$id': typeof AppWorkoutsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/ai': typeof AppAiRoute
  '/charts': typeof AppChartsRoute
  '/diary': typeof AppDiaryRoute
  '/glucose': typeof AppGlucoseRoute
  '/habits': typeof AppHabitsRoute
  '/health': typeof AppHealthRoute
  '/health-features': typeof AppHealthFeaturesRoute
  '/history': typeof AppHistoryRouteWithChildren
  '/home': typeof AppHomeRoute
  '/pregnancy': typeof AppPregnancyRoute
  '/profile': typeof AppProfileRoute
  '/recipes': typeof AppRecipesRouteWithChildren
  '/recovery': typeof AppRecoveryRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/voice': typeof AppVoiceRoute
  '/workouts': typeof AppWorkoutsRouteWithChildren
  '/legal/$doc': typeof LegalDocRoute
  '/history/$date': typeof AppHistoryDateRoute
  '/recipes/$id': typeof AppRecipesIdRoute
  '/recovery/$id': typeof AppRecoveryIdRoute
  '/workouts/$id': typeof AppWorkoutsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/charts': typeof AppChartsRoute
  '/_app/diary': typeof AppDiaryRoute
  '/_app/glucose': typeof AppGlucoseRoute
  '/_app/habits': typeof AppHabitsRoute
  '/_app/health': typeof AppHealthRoute
  '/_app/health-features': typeof AppHealthFeaturesRoute
  '/_app/history': typeof AppHistoryRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/pregnancy': typeof AppPregnancyRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/recipes': typeof AppRecipesRouteWithChildren
  '/_app/recovery': typeof AppRecoveryRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/subscription': typeof AppSubscriptionRoute
  '/_app/voice': typeof AppVoiceRoute
  '/_app/workouts': typeof AppWorkoutsRouteWithChildren
  '/legal/$doc': typeof LegalDocRoute
  '/_app/history/$date': typeof AppHistoryDateRoute
  '/_app/recipes/$id': typeof AppRecipesIdRoute
  '/_app/recovery/$id': typeof AppRecoveryIdRoute
  '/_app/workouts/$id': typeof AppWorkoutsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin'
    | '/ai'
    | '/charts'
    | '/diary'
    | '/glucose'
    | '/habits'
    | '/health'
    | '/health-features'
    | '/history'
    | '/home'
    | '/pregnancy'
    | '/profile'
    | '/recipes'
    | '/recovery'
    | '/settings'
    | '/subscription'
    | '/voice'
    | '/workouts'
    | '/legal/$doc'
    | '/history/$date'
    | '/recipes/$id'
    | '/recovery/$id'
    | '/workouts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin'
    | '/ai'
    | '/charts'
    | '/diary'
    | '/glucose'
    | '/habits'
    | '/health'
    | '/health-features'
    | '/history'
    | '/home'
    | '/pregnancy'
    | '/profile'
    | '/recipes'
    | '/recovery'
    | '/settings'
    | '/subscription'
    | '/voice'
    | '/workouts'
    | '/legal/$doc'
    | '/history/$date'
    | '/recipes/$id'
    | '/recovery/$id'
    | '/workouts/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_app/admin'
    | '/_app/ai'
    | '/_app/charts'
    | '/_app/diary'
    | '/_app/glucose'
    | '/_app/habits'
    | '/_app/health'
    | '/_app/health-features'
    | '/_app/history'
    | '/_app/home'
    | '/_app/pregnancy'
    | '/_app/profile'
    | '/_app/recipes'
    | '/_app/recovery'
    | '/_app/settings'
    | '/_app/subscription'
    | '/_app/voice'
    | '/_app/workouts'
    | '/legal/$doc'
    | '/_app/history/$date'
    | '/_app/recipes/$id'
    | '/_app/recovery/$id'
    | '/_app/workouts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LegalDocRoute: typeof LegalDocRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/charts': {
      id: '/_app/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof AppChartsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diary': {
      id: '/_app/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof AppDiaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/glucose': {
      id: '/_app/glucose'
      path: '/glucose'
      fullPath: '/glucose'
      preLoaderRoute: typeof AppGlucoseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/habits': {
      id: '/_app/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AppHabitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/health': {
      id: '/_app/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/health-features': {
      id: '/_app/health-features'
      path: '/health-features'
      fullPath: '/health-features'
      preLoaderRoute: typeof AppHealthFeaturesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pregnancy': {
      id: '/_app/pregnancy'
      path: '/pregnancy'
      fullPath: '/pregnancy'
      preLoaderRoute: typeof AppPregnancyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes': {
      id: '/_app/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AppRecipesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recovery': {
      id: '/_app/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof AppRecoveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscription': {
      id: '/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voice': {
      id: '/_app/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof AppVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workouts': {
      id: '/_app/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AppWorkoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/legal/$doc': {
      id: '/legal/$doc'
      path: '/legal/$doc'
      fullPath: '/legal/$doc'
      preLoaderRoute: typeof LegalDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/history/$date': {
      id: '/_app/history/$date'
      path: '/$date'
      fullPath: '/history/$date'
      preLoaderRoute: typeof AppHistoryDateRouteImport
      parentRoute: typeof AppHistoryRoute
    }
    '/_app/recipes/$id': {
      id: '/_app/recipes/$id'
      path: '/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof AppRecipesIdRouteImport
      parentRoute: typeof AppRecipesRoute
    }
    '/_app/recovery/$id': {
      id: '/_app/recovery/$id'
      path: '/$id'
      fullPath: '/recovery/$id'
      preLoaderRoute: typeof AppRecoveryIdRouteImport
      parentRoute: typeof AppRecoveryRoute
    }
    '/_app/workouts/$id': {
      id: '/_app/workouts/$id'
      path: '/$id'
      fullPath: '/workouts/$id'
      preLoaderRoute: typeof AppWorkoutsIdRouteImport
      parentRoute: typeof AppWorkoutsRoute
    }
  }
}

interface AppHistoryRouteChildren {
  AppHistoryDateRoute: typeof AppHistoryDateRoute
}

const AppHistoryRouteChildren: AppHistoryRouteChildren = {
  AppHistoryDateRoute: AppHistoryDateRoute,
}

const AppHistoryRouteWithChildren = AppHistoryRoute._addFileChildren(
  AppHistoryRouteChildren,
)

interface AppRecipesRouteChildren {
  AppRecipesIdRoute: typeof AppRecipesIdRoute
}

const AppRecipesRouteChildren: AppRecipesRouteChildren = {
  AppRecipesIdRoute: AppRecipesIdRoute,
}

const AppRecipesRouteWithChildren = AppRecipesRoute._addFileChildren(
  AppRecipesRouteChildren,
)

interface AppRecoveryRouteChildren {
  AppRecoveryIdRoute: typeof AppRecoveryIdRoute
}

const AppRecoveryRouteChildren: AppRecoveryRouteChildren = {
  AppRecoveryIdRoute: AppRecoveryIdRoute,
}

const AppRecoveryRouteWithChildren = AppRecoveryRoute._addFileChildren(
  AppRecoveryRouteChildren,
)

interface AppWorkoutsRouteChildren {
  AppWorkoutsIdRoute: typeof AppWorkoutsIdRoute
}

const AppWorkoutsRouteChildren: AppWorkoutsRouteChildren = {
  AppWorkoutsIdRoute: AppWorkoutsIdRoute,
}

const AppWorkoutsRouteWithChildren = AppWorkoutsRoute._addFileChildren(
  AppWorkoutsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAiRoute: typeof AppAiRoute
  AppChartsRoute: typeof AppChartsRoute
  AppDiaryRoute: typeof AppDiaryRoute
  AppGlucoseRoute: typeof AppGlucoseRoute
  AppHabitsRoute: typeof AppHabitsRoute
  AppHealthRoute: typeof AppHealthRoute
  AppHealthFeaturesRoute: typeof AppHealthFeaturesRoute
  AppHistoryRoute: typeof AppHistoryRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
  AppPregnancyRoute: typeof AppPregnancyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecipesRoute: typeof AppRecipesRouteWithChildren
  AppRecoveryRoute: typeof AppRecoveryRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppVoiceRoute: typeof AppVoiceRoute
  AppWorkoutsRoute: typeof AppWorkoutsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAiRoute: AppAiRoute,
  AppChartsRoute: AppChartsRoute,
  AppDiaryRoute: AppDiaryRoute,
  AppGlucoseRoute: AppGlucoseRoute,
  AppHabitsRoute: AppHabitsRoute,
  AppHealthRoute: AppHealthRoute,
  AppHealthFeaturesRoute: AppHealthFeaturesRoute,
  AppHistoryRoute: AppHistoryRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
  AppPregnancyRoute: AppPregnancyRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecipesRoute: AppRecipesRouteWithChildren,
  AppRecoveryRoute: AppRecoveryRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppVoiceRoute: AppVoiceRoute,
  AppWorkoutsRoute: AppWorkoutsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LegalDocRoute: LegalDocRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
